repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-build
        language: system
        entry: sh -c 'env GOROOT=$HOME/.gvm/gos/go1.24.5 $HOME/.gvm/gos/go1.24.5/bin/go build'
        args: ["build"]
        pass_filenames: false
        exclude: ^vendor/
      - id: golangci-lint
        language: system
        entry: sh -c '$HOME/.gvm/pkgsets/go1.24.5/global/bin/golangci-lint'
